/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreatorRouteImport } from './routes/$creator'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CreatorSlugRouteImport } from './routes/$creator.$slug'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiResourcesRouteImport } from './routes/api.resources'
import { Route as NNaddrRouteImport } from './routes/n.$naddr'
import { Route as RSnapshotRouteImport } from './routes/r.$snapshot'
import { Route as ApiArtifactsHashRouteImport } from './routes/api.artifacts.$hash'
import { Route as ApiOgIdRouteImport } from './routes/api.og.$id'
import { Route as ApiPreviewsIdRouteImport } from './routes/api.previews.$id'
import { Route as RSnapshotSourceRouteImport } from './routes/r.$snapshot.source'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/$creator',
  path: '/$creator',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorSlugRoute = CreatorSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CreatorRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResourcesRoute = ApiResourcesRouteImport.update({
  id: '/api/resources',
  path: '/api/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const NNaddrRoute = NNaddrRouteImport.update({
  id: '/n/$naddr',
  path: '/n/$naddr',
  getParentRoute: () => rootRouteImport,
} as any)
const RSnapshotRoute = RSnapshotRouteImport.update({
  id: '/r/$snapshot',
  path: '/r/$snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArtifactsHashRoute = ApiArtifactsHashRouteImport.update({
  id: '/api/artifacts/$hash',
  path: '/api/artifacts/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgIdRoute = ApiOgIdRouteImport.update({
  id: '/api/og/$id',
  path: '/api/og/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreviewsIdRoute = ApiPreviewsIdRouteImport.update({
  id: '/api/previews/$id',
  path: '/api/previews/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RSnapshotSourceRoute = RSnapshotSourceRouteImport.update({
  id: '/source',
  path: '/source',
  getParentRoute: () => RSnapshotRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$creator': typeof CreatorRouteWithChildren
  '/create': typeof CreateRoute
  '/$creator/$slug': typeof CreatorSlugRoute
  '/api/health': typeof ApiHealthRoute
  '/api/resources': typeof ApiResourcesRoute
  '/n/$naddr': typeof NNaddrRoute
  '/r/$snapshot': typeof RSnapshotRouteWithChildren
  '/api/artifacts/$hash': typeof ApiArtifactsHashRoute
  '/api/og/$id': typeof ApiOgIdRoute
  '/api/previews/$id': typeof ApiPreviewsIdRoute
  '/r/$snapshot/source': typeof RSnapshotSourceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$creator': typeof CreatorRouteWithChildren
  '/create': typeof CreateRoute
  '/$creator/$slug': typeof CreatorSlugRoute
  '/api/health': typeof ApiHealthRoute
  '/api/resources': typeof ApiResourcesRoute
  '/n/$naddr': typeof NNaddrRoute
  '/r/$snapshot': typeof RSnapshotRouteWithChildren
  '/api/artifacts/$hash': typeof ApiArtifactsHashRoute
  '/api/og/$id': typeof ApiOgIdRoute
  '/api/previews/$id': typeof ApiPreviewsIdRoute
  '/r/$snapshot/source': typeof RSnapshotSourceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$creator': typeof CreatorRouteWithChildren
  '/create': typeof CreateRoute
  '/$creator/$slug': typeof CreatorSlugRoute
  '/api/health': typeof ApiHealthRoute
  '/api/resources': typeof ApiResourcesRoute
  '/n/$naddr': typeof NNaddrRoute
  '/r/$snapshot': typeof RSnapshotRouteWithChildren
  '/api/artifacts/$hash': typeof ApiArtifactsHashRoute
  '/api/og/$id': typeof ApiOgIdRoute
  '/api/previews/$id': typeof ApiPreviewsIdRoute
  '/r/$snapshot/source': typeof RSnapshotSourceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$creator'
    | '/create'
    | '/$creator/$slug'
    | '/api/health'
    | '/api/resources'
    | '/n/$naddr'
    | '/r/$snapshot'
    | '/api/artifacts/$hash'
    | '/api/og/$id'
    | '/api/previews/$id'
    | '/r/$snapshot/source'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$creator'
    | '/create'
    | '/$creator/$slug'
    | '/api/health'
    | '/api/resources'
    | '/n/$naddr'
    | '/r/$snapshot'
    | '/api/artifacts/$hash'
    | '/api/og/$id'
    | '/api/previews/$id'
    | '/r/$snapshot/source'
  id:
    | '__root__'
    | '/'
    | '/$creator'
    | '/create'
    | '/$creator/$slug'
    | '/api/health'
    | '/api/resources'
    | '/n/$naddr'
    | '/r/$snapshot'
    | '/api/artifacts/$hash'
    | '/api/og/$id'
    | '/api/previews/$id'
    | '/r/$snapshot/source'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreatorRoute: typeof CreatorRouteWithChildren
  CreateRoute: typeof CreateRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiResourcesRoute: typeof ApiResourcesRoute
  NNaddrRoute: typeof NNaddrRoute
  RSnapshotRoute: typeof RSnapshotRouteWithChildren
  ApiArtifactsHashRoute: typeof ApiArtifactsHashRoute
  ApiOgIdRoute: typeof ApiOgIdRoute
  ApiPreviewsIdRoute: typeof ApiPreviewsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$creator': {
      id: '/$creator'
      path: '/$creator'
      fullPath: '/$creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$creator/$slug': {
      id: '/$creator/$slug'
      path: '/$slug'
      fullPath: '/$creator/$slug'
      preLoaderRoute: typeof CreatorSlugRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resources': {
      id: '/api/resources'
      path: '/api/resources'
      fullPath: '/api/resources'
      preLoaderRoute: typeof ApiResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n/$naddr': {
      id: '/n/$naddr'
      path: '/n/$naddr'
      fullPath: '/n/$naddr'
      preLoaderRoute: typeof NNaddrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$snapshot': {
      id: '/r/$snapshot'
      path: '/r/$snapshot'
      fullPath: '/r/$snapshot'
      preLoaderRoute: typeof RSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/artifacts/$hash': {
      id: '/api/artifacts/$hash'
      path: '/api/artifacts/$hash'
      fullPath: '/api/artifacts/$hash'
      preLoaderRoute: typeof ApiArtifactsHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/$id': {
      id: '/api/og/$id'
      path: '/api/og/$id'
      fullPath: '/api/og/$id'
      preLoaderRoute: typeof ApiOgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/previews/$id': {
      id: '/api/previews/$id'
      path: '/api/previews/$id'
      fullPath: '/api/previews/$id'
      preLoaderRoute: typeof ApiPreviewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$snapshot/source': {
      id: '/r/$snapshot/source'
      path: '/source'
      fullPath: '/r/$snapshot/source'
      preLoaderRoute: typeof RSnapshotSourceRouteImport
      parentRoute: typeof RSnapshotRoute
    }
  }
}

interface CreatorRouteChildren {
  CreatorSlugRoute: typeof CreatorSlugRoute
}

const CreatorRouteChildren: CreatorRouteChildren = {
  CreatorSlugRoute: CreatorSlugRoute,
}

const CreatorRouteWithChildren =
  CreatorRoute._addFileChildren(CreatorRouteChildren)

interface RSnapshotRouteChildren {
  RSnapshotSourceRoute: typeof RSnapshotSourceRoute
}

const RSnapshotRouteChildren: RSnapshotRouteChildren = {
  RSnapshotSourceRoute: RSnapshotSourceRoute,
}

const RSnapshotRouteWithChildren = RSnapshotRoute._addFileChildren(
  RSnapshotRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreatorRoute: CreatorRouteWithChildren,
  CreateRoute: CreateRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiResourcesRoute: ApiResourcesRoute,
  NNaddrRoute: NNaddrRoute,
  RSnapshotRoute: RSnapshotRouteWithChildren,
  ApiArtifactsHashRoute: ApiArtifactsHashRoute,
  ApiOgIdRoute: ApiOgIdRoute,
  ApiPreviewsIdRoute: ApiPreviewsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
