/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreatorRouteImport } from './routes/$creator'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CliRouteImport } from './routes/cli'
import { Route as CreateRouteImport } from './routes/create'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as CreatorSlugRouteImport } from './routes/$creator.$slug'
import { Route as ApiAdminRouteImport } from './routes/api.admin'
import { Route as ApiAdminAccessRouteImport } from './routes/api.admin-access'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiNamesRouteImport } from './routes/api.names'
import { Route as ApiProfileOgRouteImport } from './routes/api.profile-og'
import { Route as ApiPublicationsRouteImport } from './routes/api.publications'
import { Route as NNaddrRouteImport } from './routes/n.$naddr'
import { Route as PPubkeyRouteImport } from './routes/p.$pubkey'
import { Route as RSnapshotRouteImport } from './routes/r.$snapshot'
import { Route as CreatorSlugPlayRouteImport } from './routes/$creator.$slug.play'
import { Route as ApiOgIdRouteImport } from './routes/api.og.$id'
import { Route as NNaddrPlayRouteImport } from './routes/n.$naddr.play'
import { Route as RSnapshotPlayRouteImport } from './routes/r.$snapshot.play'
import { Route as RSnapshotSourceRouteImport } from './routes/r.$snapshot.source'
import { Route as CliDownloadVersionFileRouteImport } from './routes/cli.download.$version.$file'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/$creator',
  path: '/$creator',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CliRoute = CliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorSlugRoute = CreatorSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CreatorRoute,
} as any)
const ApiAdminRoute = ApiAdminRouteImport.update({
  id: '/api/admin',
  path: '/api/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAccessRoute = ApiAdminAccessRouteImport.update({
  id: '/api/admin-access',
  path: '/api/admin-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNamesRoute = ApiNamesRouteImport.update({
  id: '/api/names',
  path: '/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileOgRoute = ApiProfileOgRouteImport.update({
  id: '/api/profile-og',
  path: '/api/profile-og',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicationsRoute = ApiPublicationsRouteImport.update({
  id: '/api/publications',
  path: '/api/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const NNaddrRoute = NNaddrRouteImport.update({
  id: '/n/$naddr',
  path: '/n/$naddr',
  getParentRoute: () => rootRouteImport,
} as any)
const PPubkeyRoute = PPubkeyRouteImport.update({
  id: '/p/$pubkey',
  path: '/p/$pubkey',
  getParentRoute: () => rootRouteImport,
} as any)
const RSnapshotRoute = RSnapshotRouteImport.update({
  id: '/r/$snapshot',
  path: '/r/$snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorSlugPlayRoute = CreatorSlugPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => CreatorSlugRoute,
} as any)
const ApiOgIdRoute = ApiOgIdRouteImport.update({
  id: '/api/og/$id',
  path: '/api/og/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NNaddrPlayRoute = NNaddrPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => NNaddrRoute,
} as any)
const RSnapshotPlayRoute = RSnapshotPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => RSnapshotRoute,
} as any)
const RSnapshotSourceRoute = RSnapshotSourceRouteImport.update({
  id: '/source',
  path: '/source',
  getParentRoute: () => RSnapshotRoute,
} as any)
const CliDownloadVersionFileRoute = CliDownloadVersionFileRouteImport.update({
  id: '/download/$version/$file',
  path: '/download/$version/$file',
  getParentRoute: () => CliRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$creator': typeof CreatorRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cli': typeof CliRouteWithChildren
  '/create': typeof CreateRoute
  '/network': typeof NetworkRoute
  '/$creator/$slug': typeof CreatorSlugRouteWithChildren
  '/api/admin': typeof ApiAdminRoute
  '/api/admin-access': typeof ApiAdminAccessRoute
  '/api/health': typeof ApiHealthRoute
  '/api/names': typeof ApiNamesRoute
  '/api/profile-og': typeof ApiProfileOgRoute
  '/api/publications': typeof ApiPublicationsRoute
  '/n/$naddr': typeof NNaddrRouteWithChildren
  '/p/$pubkey': typeof PPubkeyRoute
  '/r/$snapshot': typeof RSnapshotRouteWithChildren
  '/$creator/$slug/play': typeof CreatorSlugPlayRoute
  '/api/og/$id': typeof ApiOgIdRoute
  '/n/$naddr/play': typeof NNaddrPlayRoute
  '/r/$snapshot/play': typeof RSnapshotPlayRoute
  '/r/$snapshot/source': typeof RSnapshotSourceRoute
  '/cli/download/$version/$file': typeof CliDownloadVersionFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$creator': typeof CreatorRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cli': typeof CliRouteWithChildren
  '/create': typeof CreateRoute
  '/network': typeof NetworkRoute
  '/$creator/$slug': typeof CreatorSlugRouteWithChildren
  '/api/admin': typeof ApiAdminRoute
  '/api/admin-access': typeof ApiAdminAccessRoute
  '/api/health': typeof ApiHealthRoute
  '/api/names': typeof ApiNamesRoute
  '/api/profile-og': typeof ApiProfileOgRoute
  '/api/publications': typeof ApiPublicationsRoute
  '/n/$naddr': typeof NNaddrRouteWithChildren
  '/p/$pubkey': typeof PPubkeyRoute
  '/r/$snapshot': typeof RSnapshotRouteWithChildren
  '/$creator/$slug/play': typeof CreatorSlugPlayRoute
  '/api/og/$id': typeof ApiOgIdRoute
  '/n/$naddr/play': typeof NNaddrPlayRoute
  '/r/$snapshot/play': typeof RSnapshotPlayRoute
  '/r/$snapshot/source': typeof RSnapshotSourceRoute
  '/cli/download/$version/$file': typeof CliDownloadVersionFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$creator': typeof CreatorRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cli': typeof CliRouteWithChildren
  '/create': typeof CreateRoute
  '/network': typeof NetworkRoute
  '/$creator/$slug': typeof CreatorSlugRouteWithChildren
  '/api/admin': typeof ApiAdminRoute
  '/api/admin-access': typeof ApiAdminAccessRoute
  '/api/health': typeof ApiHealthRoute
  '/api/names': typeof ApiNamesRoute
  '/api/profile-og': typeof ApiProfileOgRoute
  '/api/publications': typeof ApiPublicationsRoute
  '/n/$naddr': typeof NNaddrRouteWithChildren
  '/p/$pubkey': typeof PPubkeyRoute
  '/r/$snapshot': typeof RSnapshotRouteWithChildren
  '/$creator/$slug/play': typeof CreatorSlugPlayRoute
  '/api/og/$id': typeof ApiOgIdRoute
  '/n/$naddr/play': typeof NNaddrPlayRoute
  '/r/$snapshot/play': typeof RSnapshotPlayRoute
  '/r/$snapshot/source': typeof RSnapshotSourceRoute
  '/cli/download/$version/$file': typeof CliDownloadVersionFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$creator'
    | '/about'
    | '/admin'
    | '/cli'
    | '/create'
    | '/network'
    | '/$creator/$slug'
    | '/api/admin'
    | '/api/admin-access'
    | '/api/health'
    | '/api/names'
    | '/api/profile-og'
    | '/api/publications'
    | '/n/$naddr'
    | '/p/$pubkey'
    | '/r/$snapshot'
    | '/$creator/$slug/play'
    | '/api/og/$id'
    | '/n/$naddr/play'
    | '/r/$snapshot/play'
    | '/r/$snapshot/source'
    | '/cli/download/$version/$file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$creator'
    | '/about'
    | '/admin'
    | '/cli'
    | '/create'
    | '/network'
    | '/$creator/$slug'
    | '/api/admin'
    | '/api/admin-access'
    | '/api/health'
    | '/api/names'
    | '/api/profile-og'
    | '/api/publications'
    | '/n/$naddr'
    | '/p/$pubkey'
    | '/r/$snapshot'
    | '/$creator/$slug/play'
    | '/api/og/$id'
    | '/n/$naddr/play'
    | '/r/$snapshot/play'
    | '/r/$snapshot/source'
    | '/cli/download/$version/$file'
  id:
    | '__root__'
    | '/'
    | '/$creator'
    | '/about'
    | '/admin'
    | '/cli'
    | '/create'
    | '/network'
    | '/$creator/$slug'
    | '/api/admin'
    | '/api/admin-access'
    | '/api/health'
    | '/api/names'
    | '/api/profile-og'
    | '/api/publications'
    | '/n/$naddr'
    | '/p/$pubkey'
    | '/r/$snapshot'
    | '/$creator/$slug/play'
    | '/api/og/$id'
    | '/n/$naddr/play'
    | '/r/$snapshot/play'
    | '/r/$snapshot/source'
    | '/cli/download/$version/$file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreatorRoute: typeof CreatorRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CliRoute: typeof CliRouteWithChildren
  CreateRoute: typeof CreateRoute
  NetworkRoute: typeof NetworkRoute
  ApiAdminRoute: typeof ApiAdminRoute
  ApiAdminAccessRoute: typeof ApiAdminAccessRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiNamesRoute: typeof ApiNamesRoute
  ApiProfileOgRoute: typeof ApiProfileOgRoute
  ApiPublicationsRoute: typeof ApiPublicationsRoute
  NNaddrRoute: typeof NNaddrRouteWithChildren
  PPubkeyRoute: typeof PPubkeyRoute
  RSnapshotRoute: typeof RSnapshotRouteWithChildren
  ApiOgIdRoute: typeof ApiOgIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$creator': {
      id: '/$creator'
      path: '/$creator'
      fullPath: '/$creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli': {
      id: '/cli'
      path: '/cli'
      fullPath: '/cli'
      preLoaderRoute: typeof CliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$creator/$slug': {
      id: '/$creator/$slug'
      path: '/$slug'
      fullPath: '/$creator/$slug'
      preLoaderRoute: typeof CreatorSlugRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/api/admin': {
      id: '/api/admin'
      path: '/api/admin'
      fullPath: '/api/admin'
      preLoaderRoute: typeof ApiAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-access': {
      id: '/api/admin-access'
      path: '/api/admin-access'
      fullPath: '/api/admin-access'
      preLoaderRoute: typeof ApiAdminAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/names': {
      id: '/api/names'
      path: '/api/names'
      fullPath: '/api/names'
      preLoaderRoute: typeof ApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile-og': {
      id: '/api/profile-og'
      path: '/api/profile-og'
      fullPath: '/api/profile-og'
      preLoaderRoute: typeof ApiProfileOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/publications': {
      id: '/api/publications'
      path: '/api/publications'
      fullPath: '/api/publications'
      preLoaderRoute: typeof ApiPublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n/$naddr': {
      id: '/n/$naddr'
      path: '/n/$naddr'
      fullPath: '/n/$naddr'
      preLoaderRoute: typeof NNaddrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$pubkey': {
      id: '/p/$pubkey'
      path: '/p/$pubkey'
      fullPath: '/p/$pubkey'
      preLoaderRoute: typeof PPubkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$snapshot': {
      id: '/r/$snapshot'
      path: '/r/$snapshot'
      fullPath: '/r/$snapshot'
      preLoaderRoute: typeof RSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$creator/$slug/play': {
      id: '/$creator/$slug/play'
      path: '/play'
      fullPath: '/$creator/$slug/play'
      preLoaderRoute: typeof CreatorSlugPlayRouteImport
      parentRoute: typeof CreatorSlugRoute
    }
    '/api/og/$id': {
      id: '/api/og/$id'
      path: '/api/og/$id'
      fullPath: '/api/og/$id'
      preLoaderRoute: typeof ApiOgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n/$naddr/play': {
      id: '/n/$naddr/play'
      path: '/play'
      fullPath: '/n/$naddr/play'
      preLoaderRoute: typeof NNaddrPlayRouteImport
      parentRoute: typeof NNaddrRoute
    }
    '/r/$snapshot/play': {
      id: '/r/$snapshot/play'
      path: '/play'
      fullPath: '/r/$snapshot/play'
      preLoaderRoute: typeof RSnapshotPlayRouteImport
      parentRoute: typeof RSnapshotRoute
    }
    '/r/$snapshot/source': {
      id: '/r/$snapshot/source'
      path: '/source'
      fullPath: '/r/$snapshot/source'
      preLoaderRoute: typeof RSnapshotSourceRouteImport
      parentRoute: typeof RSnapshotRoute
    }
    '/cli/download/$version/$file': {
      id: '/cli/download/$version/$file'
      path: '/download/$version/$file'
      fullPath: '/cli/download/$version/$file'
      preLoaderRoute: typeof CliDownloadVersionFileRouteImport
      parentRoute: typeof CliRoute
    }
  }
}

interface CreatorSlugRouteChildren {
  CreatorSlugPlayRoute: typeof CreatorSlugPlayRoute
}

const CreatorSlugRouteChildren: CreatorSlugRouteChildren = {
  CreatorSlugPlayRoute: CreatorSlugPlayRoute,
}

const CreatorSlugRouteWithChildren = CreatorSlugRoute._addFileChildren(
  CreatorSlugRouteChildren,
)

interface CreatorRouteChildren {
  CreatorSlugRoute: typeof CreatorSlugRouteWithChildren
}

const CreatorRouteChildren: CreatorRouteChildren = {
  CreatorSlugRoute: CreatorSlugRouteWithChildren,
}

const CreatorRouteWithChildren =
  CreatorRoute._addFileChildren(CreatorRouteChildren)

interface CliRouteChildren {
  CliDownloadVersionFileRoute: typeof CliDownloadVersionFileRoute
}

const CliRouteChildren: CliRouteChildren = {
  CliDownloadVersionFileRoute: CliDownloadVersionFileRoute,
}

const CliRouteWithChildren = CliRoute._addFileChildren(CliRouteChildren)

interface NNaddrRouteChildren {
  NNaddrPlayRoute: typeof NNaddrPlayRoute
}

const NNaddrRouteChildren: NNaddrRouteChildren = {
  NNaddrPlayRoute: NNaddrPlayRoute,
}

const NNaddrRouteWithChildren =
  NNaddrRoute._addFileChildren(NNaddrRouteChildren)

interface RSnapshotRouteChildren {
  RSnapshotPlayRoute: typeof RSnapshotPlayRoute
  RSnapshotSourceRoute: typeof RSnapshotSourceRoute
}

const RSnapshotRouteChildren: RSnapshotRouteChildren = {
  RSnapshotPlayRoute: RSnapshotPlayRoute,
  RSnapshotSourceRoute: RSnapshotSourceRoute,
}

const RSnapshotRouteWithChildren = RSnapshotRoute._addFileChildren(
  RSnapshotRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreatorRoute: CreatorRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CliRoute: CliRouteWithChildren,
  CreateRoute: CreateRoute,
  NetworkRoute: NetworkRoute,
  ApiAdminRoute: ApiAdminRoute,
  ApiAdminAccessRoute: ApiAdminAccessRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiNamesRoute: ApiNamesRoute,
  ApiProfileOgRoute: ApiProfileOgRoute,
  ApiPublicationsRoute: ApiPublicationsRoute,
  NNaddrRoute: NNaddrRouteWithChildren,
  PPubkeyRoute: PPubkeyRoute,
  RSnapshotRoute: RSnapshotRouteWithChildren,
  ApiOgIdRoute: ApiOgIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
