/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreatorRouteImport } from './routes/$creator'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CliRouteImport } from './routes/cli'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CreatorSlugRouteImport } from './routes/$creator.$slug'
import { Route as ApiAdminRouteImport } from './routes/api.admin'
import { Route as ApiAdminAccessRouteImport } from './routes/api.admin-access'
import { Route as ApiGallerySocialRouteImport } from './routes/api.gallery-social'
import { Route as ApiGenealogyRouteImport } from './routes/api.genealogy'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiManifestRouteImport } from './routes/api.manifest'
import { Route as ApiMediaRouteImport } from './routes/api.media'
import { Route as ApiNamesRouteImport } from './routes/api.names'
import { Route as ApiProfileRouteImport } from './routes/api.profile'
import { Route as ApiProfileImageRouteImport } from './routes/api.profile-image'
import { Route as ApiProfileOgRouteImport } from './routes/api.profile-og'
import { Route as ApiProfilesRouteImport } from './routes/api.profiles'
import { Route as ApiPublicationsRouteImport } from './routes/api.publications'
import { Route as ApiResourcesRouteImport } from './routes/api.resources'
import { Route as ApiSocialRouteImport } from './routes/api.social'
import { Route as ApiSourceRouteImport } from './routes/api.source'
import { Route as ApiZapsRouteImport } from './routes/api.zaps'
import { Route as NNaddrRouteImport } from './routes/n.$naddr'
import { Route as PPubkeyRouteImport } from './routes/p.$pubkey'
import { Route as RSnapshotRouteImport } from './routes/r.$snapshot'
import { Route as CreatorSlugPlayRouteImport } from './routes/$creator.$slug.play'
import { Route as ApiArtifactsHashRouteImport } from './routes/api.artifacts.$hash'
import { Route as ApiCommentMediaIdRouteImport } from './routes/api.comment-media.$id'
import { Route as ApiOgIdRouteImport } from './routes/api.og.$id'
import { Route as ApiPreviewVideosIdRouteImport } from './routes/api.preview-videos.$id'
import { Route as ApiPreviewsIdRouteImport } from './routes/api.previews.$id'
import { Route as NNaddrPlayRouteImport } from './routes/n.$naddr.play'
import { Route as RSnapshotPlayRouteImport } from './routes/r.$snapshot.play'
import { Route as RSnapshotSourceRouteImport } from './routes/r.$snapshot.source'
import { Route as CliDownloadVersionFileRouteImport } from './routes/cli.download.$version.$file'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/$creator',
  path: '/$creator',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CliRoute = CliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorSlugRoute = CreatorSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CreatorRoute,
} as any)
const ApiAdminRoute = ApiAdminRouteImport.update({
  id: '/api/admin',
  path: '/api/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAccessRoute = ApiAdminAccessRouteImport.update({
  id: '/api/admin-access',
  path: '/api/admin-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGallerySocialRoute = ApiGallerySocialRouteImport.update({
  id: '/api/gallery-social',
  path: '/api/gallery-social',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenealogyRoute = ApiGenealogyRouteImport.update({
  id: '/api/genealogy',
  path: '/api/genealogy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiManifestRoute = ApiManifestRouteImport.update({
  id: '/api/manifest',
  path: '/api/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNamesRoute = ApiNamesRouteImport.update({
  id: '/api/names',
  path: '/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileImageRoute = ApiProfileImageRouteImport.update({
  id: '/api/profile-image',
  path: '/api/profile-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileOgRoute = ApiProfileOgRouteImport.update({
  id: '/api/profile-og',
  path: '/api/profile-og',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilesRoute = ApiProfilesRouteImport.update({
  id: '/api/profiles',
  path: '/api/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicationsRoute = ApiPublicationsRouteImport.update({
  id: '/api/publications',
  path: '/api/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResourcesRoute = ApiResourcesRouteImport.update({
  id: '/api/resources',
  path: '/api/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSocialRoute = ApiSocialRouteImport.update({
  id: '/api/social',
  path: '/api/social',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSourceRoute = ApiSourceRouteImport.update({
  id: '/api/source',
  path: '/api/source',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZapsRoute = ApiZapsRouteImport.update({
  id: '/api/zaps',
  path: '/api/zaps',
  getParentRoute: () => rootRouteImport,
} as any)
const NNaddrRoute = NNaddrRouteImport.update({
  id: '/n/$naddr',
  path: '/n/$naddr',
  getParentRoute: () => rootRouteImport,
} as any)
const PPubkeyRoute = PPubkeyRouteImport.update({
  id: '/p/$pubkey',
  path: '/p/$pubkey',
  getParentRoute: () => rootRouteImport,
} as any)
const RSnapshotRoute = RSnapshotRouteImport.update({
  id: '/r/$snapshot',
  path: '/r/$snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorSlugPlayRoute = CreatorSlugPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => CreatorSlugRoute,
} as any)
const ApiArtifactsHashRoute = ApiArtifactsHashRouteImport.update({
  id: '/api/artifacts/$hash',
  path: '/api/artifacts/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommentMediaIdRoute = ApiCommentMediaIdRouteImport.update({
  id: '/api/comment-media/$id',
  path: '/api/comment-media/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgIdRoute = ApiOgIdRouteImport.update({
  id: '/api/og/$id',
  path: '/api/og/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreviewVideosIdRoute = ApiPreviewVideosIdRouteImport.update({
  id: '/api/preview-videos/$id',
  path: '/api/preview-videos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreviewsIdRoute = ApiPreviewsIdRouteImport.update({
  id: '/api/previews/$id',
  path: '/api/previews/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NNaddrPlayRoute = NNaddrPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => NNaddrRoute,
} as any)
const RSnapshotPlayRoute = RSnapshotPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => RSnapshotRoute,
} as any)
const RSnapshotSourceRoute = RSnapshotSourceRouteImport.update({
  id: '/source',
  path: '/source',
  getParentRoute: () => RSnapshotRoute,
} as any)
const CliDownloadVersionFileRoute = CliDownloadVersionFileRouteImport.update({
  id: '/download/$version/$file',
  path: '/download/$version/$file',
  getParentRoute: () => CliRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$creator': typeof CreatorRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cli': typeof CliRouteWithChildren
  '/create': typeof CreateRoute
  '/$creator/$slug': typeof CreatorSlugRouteWithChildren
  '/api/admin': typeof ApiAdminRoute
  '/api/admin-access': typeof ApiAdminAccessRoute
  '/api/gallery-social': typeof ApiGallerySocialRoute
  '/api/genealogy': typeof ApiGenealogyRoute
  '/api/health': typeof ApiHealthRoute
  '/api/manifest': typeof ApiManifestRoute
  '/api/media': typeof ApiMediaRoute
  '/api/names': typeof ApiNamesRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/profile-image': typeof ApiProfileImageRoute
  '/api/profile-og': typeof ApiProfileOgRoute
  '/api/profiles': typeof ApiProfilesRoute
  '/api/publications': typeof ApiPublicationsRoute
  '/api/resources': typeof ApiResourcesRoute
  '/api/social': typeof ApiSocialRoute
  '/api/source': typeof ApiSourceRoute
  '/api/zaps': typeof ApiZapsRoute
  '/n/$naddr': typeof NNaddrRouteWithChildren
  '/p/$pubkey': typeof PPubkeyRoute
  '/r/$snapshot': typeof RSnapshotRouteWithChildren
  '/$creator/$slug/play': typeof CreatorSlugPlayRoute
  '/api/artifacts/$hash': typeof ApiArtifactsHashRoute
  '/api/comment-media/$id': typeof ApiCommentMediaIdRoute
  '/api/og/$id': typeof ApiOgIdRoute
  '/api/preview-videos/$id': typeof ApiPreviewVideosIdRoute
  '/api/previews/$id': typeof ApiPreviewsIdRoute
  '/n/$naddr/play': typeof NNaddrPlayRoute
  '/r/$snapshot/play': typeof RSnapshotPlayRoute
  '/r/$snapshot/source': typeof RSnapshotSourceRoute
  '/cli/download/$version/$file': typeof CliDownloadVersionFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$creator': typeof CreatorRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cli': typeof CliRouteWithChildren
  '/create': typeof CreateRoute
  '/$creator/$slug': typeof CreatorSlugRouteWithChildren
  '/api/admin': typeof ApiAdminRoute
  '/api/admin-access': typeof ApiAdminAccessRoute
  '/api/gallery-social': typeof ApiGallerySocialRoute
  '/api/genealogy': typeof ApiGenealogyRoute
  '/api/health': typeof ApiHealthRoute
  '/api/manifest': typeof ApiManifestRoute
  '/api/media': typeof ApiMediaRoute
  '/api/names': typeof ApiNamesRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/profile-image': typeof ApiProfileImageRoute
  '/api/profile-og': typeof ApiProfileOgRoute
  '/api/profiles': typeof ApiProfilesRoute
  '/api/publications': typeof ApiPublicationsRoute
  '/api/resources': typeof ApiResourcesRoute
  '/api/social': typeof ApiSocialRoute
  '/api/source': typeof ApiSourceRoute
  '/api/zaps': typeof ApiZapsRoute
  '/n/$naddr': typeof NNaddrRouteWithChildren
  '/p/$pubkey': typeof PPubkeyRoute
  '/r/$snapshot': typeof RSnapshotRouteWithChildren
  '/$creator/$slug/play': typeof CreatorSlugPlayRoute
  '/api/artifacts/$hash': typeof ApiArtifactsHashRoute
  '/api/comment-media/$id': typeof ApiCommentMediaIdRoute
  '/api/og/$id': typeof ApiOgIdRoute
  '/api/preview-videos/$id': typeof ApiPreviewVideosIdRoute
  '/api/previews/$id': typeof ApiPreviewsIdRoute
  '/n/$naddr/play': typeof NNaddrPlayRoute
  '/r/$snapshot/play': typeof RSnapshotPlayRoute
  '/r/$snapshot/source': typeof RSnapshotSourceRoute
  '/cli/download/$version/$file': typeof CliDownloadVersionFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$creator': typeof CreatorRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cli': typeof CliRouteWithChildren
  '/create': typeof CreateRoute
  '/$creator/$slug': typeof CreatorSlugRouteWithChildren
  '/api/admin': typeof ApiAdminRoute
  '/api/admin-access': typeof ApiAdminAccessRoute
  '/api/gallery-social': typeof ApiGallerySocialRoute
  '/api/genealogy': typeof ApiGenealogyRoute
  '/api/health': typeof ApiHealthRoute
  '/api/manifest': typeof ApiManifestRoute
  '/api/media': typeof ApiMediaRoute
  '/api/names': typeof ApiNamesRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/profile-image': typeof ApiProfileImageRoute
  '/api/profile-og': typeof ApiProfileOgRoute
  '/api/profiles': typeof ApiProfilesRoute
  '/api/publications': typeof ApiPublicationsRoute
  '/api/resources': typeof ApiResourcesRoute
  '/api/social': typeof ApiSocialRoute
  '/api/source': typeof ApiSourceRoute
  '/api/zaps': typeof ApiZapsRoute
  '/n/$naddr': typeof NNaddrRouteWithChildren
  '/p/$pubkey': typeof PPubkeyRoute
  '/r/$snapshot': typeof RSnapshotRouteWithChildren
  '/$creator/$slug/play': typeof CreatorSlugPlayRoute
  '/api/artifacts/$hash': typeof ApiArtifactsHashRoute
  '/api/comment-media/$id': typeof ApiCommentMediaIdRoute
  '/api/og/$id': typeof ApiOgIdRoute
  '/api/preview-videos/$id': typeof ApiPreviewVideosIdRoute
  '/api/previews/$id': typeof ApiPreviewsIdRoute
  '/n/$naddr/play': typeof NNaddrPlayRoute
  '/r/$snapshot/play': typeof RSnapshotPlayRoute
  '/r/$snapshot/source': typeof RSnapshotSourceRoute
  '/cli/download/$version/$file': typeof CliDownloadVersionFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$creator'
    | '/about'
    | '/admin'
    | '/cli'
    | '/create'
    | '/$creator/$slug'
    | '/api/admin'
    | '/api/admin-access'
    | '/api/gallery-social'
    | '/api/genealogy'
    | '/api/health'
    | '/api/manifest'
    | '/api/media'
    | '/api/names'
    | '/api/profile'
    | '/api/profile-image'
    | '/api/profile-og'
    | '/api/profiles'
    | '/api/publications'
    | '/api/resources'
    | '/api/social'
    | '/api/source'
    | '/api/zaps'
    | '/n/$naddr'
    | '/p/$pubkey'
    | '/r/$snapshot'
    | '/$creator/$slug/play'
    | '/api/artifacts/$hash'
    | '/api/comment-media/$id'
    | '/api/og/$id'
    | '/api/preview-videos/$id'
    | '/api/previews/$id'
    | '/n/$naddr/play'
    | '/r/$snapshot/play'
    | '/r/$snapshot/source'
    | '/cli/download/$version/$file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$creator'
    | '/about'
    | '/admin'
    | '/cli'
    | '/create'
    | '/$creator/$slug'
    | '/api/admin'
    | '/api/admin-access'
    | '/api/gallery-social'
    | '/api/genealogy'
    | '/api/health'
    | '/api/manifest'
    | '/api/media'
    | '/api/names'
    | '/api/profile'
    | '/api/profile-image'
    | '/api/profile-og'
    | '/api/profiles'
    | '/api/publications'
    | '/api/resources'
    | '/api/social'
    | '/api/source'
    | '/api/zaps'
    | '/n/$naddr'
    | '/p/$pubkey'
    | '/r/$snapshot'
    | '/$creator/$slug/play'
    | '/api/artifacts/$hash'
    | '/api/comment-media/$id'
    | '/api/og/$id'
    | '/api/preview-videos/$id'
    | '/api/previews/$id'
    | '/n/$naddr/play'
    | '/r/$snapshot/play'
    | '/r/$snapshot/source'
    | '/cli/download/$version/$file'
  id:
    | '__root__'
    | '/'
    | '/$creator'
    | '/about'
    | '/admin'
    | '/cli'
    | '/create'
    | '/$creator/$slug'
    | '/api/admin'
    | '/api/admin-access'
    | '/api/gallery-social'
    | '/api/genealogy'
    | '/api/health'
    | '/api/manifest'
    | '/api/media'
    | '/api/names'
    | '/api/profile'
    | '/api/profile-image'
    | '/api/profile-og'
    | '/api/profiles'
    | '/api/publications'
    | '/api/resources'
    | '/api/social'
    | '/api/source'
    | '/api/zaps'
    | '/n/$naddr'
    | '/p/$pubkey'
    | '/r/$snapshot'
    | '/$creator/$slug/play'
    | '/api/artifacts/$hash'
    | '/api/comment-media/$id'
    | '/api/og/$id'
    | '/api/preview-videos/$id'
    | '/api/previews/$id'
    | '/n/$naddr/play'
    | '/r/$snapshot/play'
    | '/r/$snapshot/source'
    | '/cli/download/$version/$file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreatorRoute: typeof CreatorRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CliRoute: typeof CliRouteWithChildren
  CreateRoute: typeof CreateRoute
  ApiAdminRoute: typeof ApiAdminRoute
  ApiAdminAccessRoute: typeof ApiAdminAccessRoute
  ApiGallerySocialRoute: typeof ApiGallerySocialRoute
  ApiGenealogyRoute: typeof ApiGenealogyRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiManifestRoute: typeof ApiManifestRoute
  ApiMediaRoute: typeof ApiMediaRoute
  ApiNamesRoute: typeof ApiNamesRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiProfileImageRoute: typeof ApiProfileImageRoute
  ApiProfileOgRoute: typeof ApiProfileOgRoute
  ApiProfilesRoute: typeof ApiProfilesRoute
  ApiPublicationsRoute: typeof ApiPublicationsRoute
  ApiResourcesRoute: typeof ApiResourcesRoute
  ApiSocialRoute: typeof ApiSocialRoute
  ApiSourceRoute: typeof ApiSourceRoute
  ApiZapsRoute: typeof ApiZapsRoute
  NNaddrRoute: typeof NNaddrRouteWithChildren
  PPubkeyRoute: typeof PPubkeyRoute
  RSnapshotRoute: typeof RSnapshotRouteWithChildren
  ApiArtifactsHashRoute: typeof ApiArtifactsHashRoute
  ApiCommentMediaIdRoute: typeof ApiCommentMediaIdRoute
  ApiOgIdRoute: typeof ApiOgIdRoute
  ApiPreviewVideosIdRoute: typeof ApiPreviewVideosIdRoute
  ApiPreviewsIdRoute: typeof ApiPreviewsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$creator': {
      id: '/$creator'
      path: '/$creator'
      fullPath: '/$creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli': {
      id: '/cli'
      path: '/cli'
      fullPath: '/cli'
      preLoaderRoute: typeof CliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$creator/$slug': {
      id: '/$creator/$slug'
      path: '/$slug'
      fullPath: '/$creator/$slug'
      preLoaderRoute: typeof CreatorSlugRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/api/admin': {
      id: '/api/admin'
      path: '/api/admin'
      fullPath: '/api/admin'
      preLoaderRoute: typeof ApiAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-access': {
      id: '/api/admin-access'
      path: '/api/admin-access'
      fullPath: '/api/admin-access'
      preLoaderRoute: typeof ApiAdminAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gallery-social': {
      id: '/api/gallery-social'
      path: '/api/gallery-social'
      fullPath: '/api/gallery-social'
      preLoaderRoute: typeof ApiGallerySocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/genealogy': {
      id: '/api/genealogy'
      path: '/api/genealogy'
      fullPath: '/api/genealogy'
      preLoaderRoute: typeof ApiGenealogyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/manifest': {
      id: '/api/manifest'
      path: '/api/manifest'
      fullPath: '/api/manifest'
      preLoaderRoute: typeof ApiManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/names': {
      id: '/api/names'
      path: '/api/names'
      fullPath: '/api/names'
      preLoaderRoute: typeof ApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile-image': {
      id: '/api/profile-image'
      path: '/api/profile-image'
      fullPath: '/api/profile-image'
      preLoaderRoute: typeof ApiProfileImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile-og': {
      id: '/api/profile-og'
      path: '/api/profile-og'
      fullPath: '/api/profile-og'
      preLoaderRoute: typeof ApiProfileOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profiles': {
      id: '/api/profiles'
      path: '/api/profiles'
      fullPath: '/api/profiles'
      preLoaderRoute: typeof ApiProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/publications': {
      id: '/api/publications'
      path: '/api/publications'
      fullPath: '/api/publications'
      preLoaderRoute: typeof ApiPublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resources': {
      id: '/api/resources'
      path: '/api/resources'
      fullPath: '/api/resources'
      preLoaderRoute: typeof ApiResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/social': {
      id: '/api/social'
      path: '/api/social'
      fullPath: '/api/social'
      preLoaderRoute: typeof ApiSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/source': {
      id: '/api/source'
      path: '/api/source'
      fullPath: '/api/source'
      preLoaderRoute: typeof ApiSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zaps': {
      id: '/api/zaps'
      path: '/api/zaps'
      fullPath: '/api/zaps'
      preLoaderRoute: typeof ApiZapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n/$naddr': {
      id: '/n/$naddr'
      path: '/n/$naddr'
      fullPath: '/n/$naddr'
      preLoaderRoute: typeof NNaddrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$pubkey': {
      id: '/p/$pubkey'
      path: '/p/$pubkey'
      fullPath: '/p/$pubkey'
      preLoaderRoute: typeof PPubkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$snapshot': {
      id: '/r/$snapshot'
      path: '/r/$snapshot'
      fullPath: '/r/$snapshot'
      preLoaderRoute: typeof RSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$creator/$slug/play': {
      id: '/$creator/$slug/play'
      path: '/play'
      fullPath: '/$creator/$slug/play'
      preLoaderRoute: typeof CreatorSlugPlayRouteImport
      parentRoute: typeof CreatorSlugRoute
    }
    '/api/artifacts/$hash': {
      id: '/api/artifacts/$hash'
      path: '/api/artifacts/$hash'
      fullPath: '/api/artifacts/$hash'
      preLoaderRoute: typeof ApiArtifactsHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comment-media/$id': {
      id: '/api/comment-media/$id'
      path: '/api/comment-media/$id'
      fullPath: '/api/comment-media/$id'
      preLoaderRoute: typeof ApiCommentMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/$id': {
      id: '/api/og/$id'
      path: '/api/og/$id'
      fullPath: '/api/og/$id'
      preLoaderRoute: typeof ApiOgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preview-videos/$id': {
      id: '/api/preview-videos/$id'
      path: '/api/preview-videos/$id'
      fullPath: '/api/preview-videos/$id'
      preLoaderRoute: typeof ApiPreviewVideosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/previews/$id': {
      id: '/api/previews/$id'
      path: '/api/previews/$id'
      fullPath: '/api/previews/$id'
      preLoaderRoute: typeof ApiPreviewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n/$naddr/play': {
      id: '/n/$naddr/play'
      path: '/play'
      fullPath: '/n/$naddr/play'
      preLoaderRoute: typeof NNaddrPlayRouteImport
      parentRoute: typeof NNaddrRoute
    }
    '/r/$snapshot/play': {
      id: '/r/$snapshot/play'
      path: '/play'
      fullPath: '/r/$snapshot/play'
      preLoaderRoute: typeof RSnapshotPlayRouteImport
      parentRoute: typeof RSnapshotRoute
    }
    '/r/$snapshot/source': {
      id: '/r/$snapshot/source'
      path: '/source'
      fullPath: '/r/$snapshot/source'
      preLoaderRoute: typeof RSnapshotSourceRouteImport
      parentRoute: typeof RSnapshotRoute
    }
    '/cli/download/$version/$file': {
      id: '/cli/download/$version/$file'
      path: '/download/$version/$file'
      fullPath: '/cli/download/$version/$file'
      preLoaderRoute: typeof CliDownloadVersionFileRouteImport
      parentRoute: typeof CliRoute
    }
  }
}

interface CreatorSlugRouteChildren {
  CreatorSlugPlayRoute: typeof CreatorSlugPlayRoute
}

const CreatorSlugRouteChildren: CreatorSlugRouteChildren = {
  CreatorSlugPlayRoute: CreatorSlugPlayRoute,
}

const CreatorSlugRouteWithChildren = CreatorSlugRoute._addFileChildren(
  CreatorSlugRouteChildren,
)

interface CreatorRouteChildren {
  CreatorSlugRoute: typeof CreatorSlugRouteWithChildren
}

const CreatorRouteChildren: CreatorRouteChildren = {
  CreatorSlugRoute: CreatorSlugRouteWithChildren,
}

const CreatorRouteWithChildren =
  CreatorRoute._addFileChildren(CreatorRouteChildren)

interface CliRouteChildren {
  CliDownloadVersionFileRoute: typeof CliDownloadVersionFileRoute
}

const CliRouteChildren: CliRouteChildren = {
  CliDownloadVersionFileRoute: CliDownloadVersionFileRoute,
}

const CliRouteWithChildren = CliRoute._addFileChildren(CliRouteChildren)

interface NNaddrRouteChildren {
  NNaddrPlayRoute: typeof NNaddrPlayRoute
}

const NNaddrRouteChildren: NNaddrRouteChildren = {
  NNaddrPlayRoute: NNaddrPlayRoute,
}

const NNaddrRouteWithChildren =
  NNaddrRoute._addFileChildren(NNaddrRouteChildren)

interface RSnapshotRouteChildren {
  RSnapshotPlayRoute: typeof RSnapshotPlayRoute
  RSnapshotSourceRoute: typeof RSnapshotSourceRoute
}

const RSnapshotRouteChildren: RSnapshotRouteChildren = {
  RSnapshotPlayRoute: RSnapshotPlayRoute,
  RSnapshotSourceRoute: RSnapshotSourceRoute,
}

const RSnapshotRouteWithChildren = RSnapshotRoute._addFileChildren(
  RSnapshotRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreatorRoute: CreatorRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CliRoute: CliRouteWithChildren,
  CreateRoute: CreateRoute,
  ApiAdminRoute: ApiAdminRoute,
  ApiAdminAccessRoute: ApiAdminAccessRoute,
  ApiGallerySocialRoute: ApiGallerySocialRoute,
  ApiGenealogyRoute: ApiGenealogyRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiManifestRoute: ApiManifestRoute,
  ApiMediaRoute: ApiMediaRoute,
  ApiNamesRoute: ApiNamesRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiProfileImageRoute: ApiProfileImageRoute,
  ApiProfileOgRoute: ApiProfileOgRoute,
  ApiProfilesRoute: ApiProfilesRoute,
  ApiPublicationsRoute: ApiPublicationsRoute,
  ApiResourcesRoute: ApiResourcesRoute,
  ApiSocialRoute: ApiSocialRoute,
  ApiSourceRoute: ApiSourceRoute,
  ApiZapsRoute: ApiZapsRoute,
  NNaddrRoute: NNaddrRouteWithChildren,
  PPubkeyRoute: PPubkeyRoute,
  RSnapshotRoute: RSnapshotRouteWithChildren,
  ApiArtifactsHashRoute: ApiArtifactsHashRoute,
  ApiCommentMediaIdRoute: ApiCommentMediaIdRoute,
  ApiOgIdRoute: ApiOgIdRoute,
  ApiPreviewVideosIdRoute: ApiPreviewVideosIdRoute,
  ApiPreviewsIdRoute: ApiPreviewsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
