// Explicit sources keep local draft artwork out of the site's production routes.
export const spriteLibrary = [
  {
    id: 'laptop',
    label: 'Typing',
    columns: 3,
    rows: 3,
    detail: 'Original · in use',
    file: 'apps/web/public/brand/soybert-laptop.png',
    hint: 'Use a sharp corner of the laptop. Avoid a hand or an eye that blinks.',
  },
  {
    id: 'walking',
    label: 'Walking',
    columns: 3,
    rows: 3,
    detail: 'Original · in use',
    file: 'apps/web/public/brand/soybert-walking.png',
    hint: 'Use a stable corner of Soybert’s body. Avoid the moving feet so the stride stays intact.',
  },
  {
    id: 'error',
    label: 'Error',
    columns: 3,
    rows: 2,
    detail: 'Draft · 6 frames',
    file: 'output/imagegen/mascot-cycles/error.png',
    hint: 'Choose a consistent point on the body. Aligning a point also removes its intentional movement.',
  },
  {
    id: 'success',
    label: 'Celebrate',
    columns: 3,
    rows: 2,
    detail: 'Draft · 6 frames',
    file: 'output/imagegen/mascot-cycles/success.png',
    hint: 'Choose a consistent body point. The existing background and artwork changes are retained.',
  },
  {
    id: 'warning',
    label: 'Warning',
    columns: 3,
    rows: 2,
    detail: 'Draft · 6 frames',
    file: 'output/imagegen/mascot-cycles/warning.png',
    hint: 'Choose a corner of the body, rather than the eyes or warning symbol.',
  },
  {
    id: 'walking-legacy',
    label: 'Walking / old',
    columns: 3,
    rows: 2,
    detail: 'Previous · 6 frames',
    file: 'output/imagegen/mascot-cycles/loading.png',
    hint: 'This is the older six-frame walk. Choose Walking for the new nine-frame sheet.',
  },
];
