import { PublishError } from '../../publish/src/config';
import { z } from 'zod';
import { mkdir, open, rename, rm, lstat } from 'node:fs/promises';
import { join } from 'node:path';
import { sha256 } from '../../protocol/src';
import { resourceMime } from '../../client/src/resource-mime';
import { regularFile, checkSource } from '../../publish/src/project';

export const ASSET_LOCK = 'napplet.assets.json';
export const ASSET_MODULE = 'soy-assets.js';
export const ASSET_TYPES = 'soy-assets.d.ts';
const assetTypes =
  '// Generated by soyLI.\nexport function assetUrl(id: string): Promise<string>;\nexport function releaseAssetUrls(): void;\n';
export const MAX_ASSET_BYTES = 10 * 1024 * 1024;
export const assetSchema = z
  .object({
    id: z.string().regex(/^[a-z][a-z0-9-]{0,47}$/),
    path: z.string().regex(/^assets\/[a-f0-9]{64}\.[a-z0-9]{2,5}$/),
    hash: z.string().regex(/^[a-f0-9]{64}$/),
    bytes: z.number().int().positive().max(MAX_ASSET_BYTES),
    mime: z.string().max(80),
    storage: z.enum(['embedded', 'external']),
    license: z.string().min(1).max(160),
    source: z.string().max(500).default(''),
  })
  .strict();
export type ManagedAsset = z.infer<typeof assetSchema>;
export const assetLockSchema = z
  .object({ version: z.literal(1), assets: z.array(assetSchema).max(32) })
  .strict()
  .refine(
    (v) => v.assets.reduce((sum, a) => sum + a.bytes, 0) <= 32 * 1024 * 1024,
    'Managed assets exceed the current 32 MiB project budget.',
  )
  .refine(
    (v) => new Set(v.assets.map((a) => a.id)).size === v.assets.length,
    'Duplicate asset names',
  );
export type AssetLock = z.infer<typeof assetLockSchema>;
export function parseAssets(bytes?: Uint8Array): AssetLock {
  if (!bytes) return { version: 1, assets: [] };
  try {
    return assetLockSchema.parse(JSON.parse(new TextDecoder().decode(bytes)));
  } catch {
    throw new PublishError(
      'ASSET_INVALID',
      'Invalid napplet.assets.json. Use unique asset names, supported metadata, at most 32 assets and 32 MiB total (10 MiB each).',
    );
  }
}
export async function readAssets(root: string) {
  try {
    return parseAssets(await regularFile(root, ASSET_LOCK, 65536));
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return parseAssets();
    throw error;
  }
}
const formats: Record<string, string> = {
  'image/png': 'png',
  'image/jpeg': 'jpg',
  'image/webp': 'webp',
  'image/gif': 'gif',
  'audio/wav': 'wav',
  'audio/ogg': 'ogg',
  'audio/mpeg': 'mp3',
  'font/woff': 'woff',
  'font/woff2': 'woff2',
  'video/mp4': 'mp4',
  'video/webm': 'webm',
};
export function assetMime(bytes: Uint8Array) {
  const mime = resourceMime(bytes, true);
  if (!formats[mime])
    throw new PublishError(
      'ASSET_INVALID',
      'Use a PNG, JPEG, WebP, GIF, WAV, Ogg, MP3, WOFF, WOFF2, MP4 or WebM asset.',
    );
  return mime;
}
export async function verifyAsset(asset: ManagedAsset, bytes: Uint8Array) {
  if (
    bytes.length !== asset.bytes ||
    (await sha256(bytes)) !== asset.hash ||
    assetMime(bytes) !== asset.mime
  )
    throw new PublishError(
      'ASSET_INVALID',
      `Asset ${asset.id} changed or is corrupt. Import it again before building or publishing.`,
    );
  checkSource(asset.path, bytes);
}
export async function assetBytes(root: string, asset: ManagedAsset) {
  const bytes = await regularFile(root, asset.path, MAX_ASSET_BYTES);
  await verifyAsset(asset, bytes);
  return bytes;
}

/** Portable build helper: external requests use the standard resource capability and host server hints. */
export function assetModule(lock: AssetLock) {
  const imports = lock.assets
    .filter((a) => a.storage === 'embedded')
    .map((a, i) => `import embedded${i} from ${JSON.stringify('./' + a.path + '?url')};`);
  let i = 0;
  const entries = lock.assets.map(
    (a) =>
      `${JSON.stringify(a.id)}: ${a.storage === 'embedded' ? `{url: embedded${i++}}` : `{hash: ${JSON.stringify(a.hash)}}`}`,
  );
  return `// Generated by soyLI. Edit napplet.assets.json through soyli assets or the manager.\n${imports.join('\n')}\nconst assets = {${entries.join(',\n')}};\nconst urls = new Map();\n/** @param {string} id */\nexport async function assetUrl(id) {\n  const entry = Object.hasOwn(assets, id) ? assets[id] : undefined;\n  if (!entry) throw new PublishError('ASSET_INVALID', 'Unknown asset: ' + id);\n  if (entry.url) return entry.url;\n  if (!urls.has(id)) {\n    const pending = window.napplet.resource.bytes('blossom:sha256:' + entry.hash).then(blob => URL.createObjectURL(blob));\n    urls.set(id, pending);\n    pending.catch(() => { if (urls.get(id) === pending) urls.delete(id); });\n  }\n  return urls.get(id);\n}\nexport function releaseAssetUrls() {\n  for (const value of urls.values()) value.then(url => URL.revokeObjectURL(url)).catch(() => {});\n  urls.clear();\n}\n`;
}
async function replaceFile(root: string, path: string, bytes: string | Uint8Array) {
  const previous = await lstat(join(root, path)).catch((e) => {
    if (e.code !== 'ENOENT') throw e;
    return null;
  });
  if (previous && (!previous.isFile() || previous.isSymbolicLink()))
    throw new PublishError('ASSET_INVALID', 'Unsafe project file.');
  const temporary = join(root, `.soyli-${crypto.randomUUID()}.tmp`);
  const file = await open(temporary, 'wx', 0o600);
  try {
    await file.writeFile(bytes);
    await file.sync();
    await file.close();
    await rename(temporary, join(root, path));
  } finally {
    await file.close();
    await rm(temporary, { force: true });
  }
}
export async function saveAssets(root: string, lock: AssetLock) {
  parseAssets(new TextEncoder().encode(JSON.stringify(lock)));
  const existing = await regularFile(root, ASSET_MODULE, 65536).catch((error) => {
    if (error.code !== 'ENOENT') throw error;
    return null;
  });
  if (existing && !new TextDecoder().decode(existing).startsWith('// Generated by soyLI.'))
    throw new PublishError(
      'ASSET_INVALID',
      'soy-assets.js already exists and is not generated by soyLI. Move it aside explicitly.',
    );
  const existingTypes = await regularFile(root, ASSET_TYPES, 65536).catch((error) => {
    if (error.code !== 'ENOENT') throw error;
    return null;
  });
  if (
    existingTypes &&
    !new TextDecoder().decode(existingTypes).startsWith('// Generated by soyLI.')
  )
    throw new PublishError(
      'ASSET_INVALID',
      'soy-assets.d.ts already exists and is not generated by soyLI. Move it aside explicitly.',
    );
  await replaceFile(root, ASSET_TYPES, assetTypes);
  // Write the lock last; a partial update is detected by validateAssets before publish.
  await replaceFile(root, ASSET_MODULE, assetModule(lock));
  await replaceFile(root, ASSET_LOCK, JSON.stringify(lock, null, 2) + '\n');
}
export async function importAsset(
  root: string,
  input: {
    id: string;
    bytes: Uint8Array;
    storage: 'embedded' | 'external';
    license: string;
    source?: string;
  },
) {
  const lock = await readAssets(root);
  if (lock.assets.some((a) => a.id === input.id))
    throw new PublishError(
      'ASSET_INVALID',
      'This asset name already exists. Choose another name; originals are never overwritten.',
    );
  const mime = assetMime(input.bytes),
    hash = await sha256(input.bytes);
  const parsedAsset = assetSchema.safeParse({
    id: input.id,
    hash,
    bytes: input.bytes.length,
    path: `assets/${hash}.${formats[mime]}`,
    mime,
    storage: input.storage,
    license: input.license,
    source: input.source ?? '',
  });
  if (!parsedAsset.success)
    throw new PublishError(
      'ASSET_INVALID',
      'Choose a lowercase asset name, embedded/external storage, a license/credit and a non-empty file up to 10 MiB.',
    );
  const asset = parsedAsset.data;
  const next = parseAssets(
    new TextEncoder().encode(JSON.stringify({ version: 1, assets: [...lock.assets, asset] })),
  );
  if (next.assets.reduce((sum, a) => sum + a.bytes, 0) > 32 * 1024 * 1024)
    throw new PublishError(
      'ASSET_INVALID',
      'Managed assets exceed the current 32 MiB project budget (source is capped at 40 MiB). This is a tooling limit, not a storage plan.',
    );
  checkSource(asset.path, input.bytes);
  await mkdir(join(root, 'assets'), { recursive: true });
  if ((await lstat(join(root, 'assets'))).isSymbolicLink())
    throw new PublishError('ASSET_INVALID', 'Asset directory cannot be a symlink.');
  try {
    const file = await open(join(root, asset.path), 'wx', 0o644);
    try {
      await file.writeFile(input.bytes);
      await file.sync();
    } finally {
      await file.close();
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'EEXIST') throw error;
    await assetBytes(root, asset);
  }
  await saveAssets(root, next);
  return asset;
}
export async function validateAssets(root: string) {
  const lock = await readAssets(root);
  for (const asset of lock.assets) await assetBytes(root, asset);
  if (
    lock.assets.length &&
    (new TextDecoder().decode(await regularFile(root, ASSET_MODULE, 65536)) !== assetModule(lock) ||
      new TextDecoder().decode(await regularFile(root, ASSET_TYPES, 65536)) !== assetTypes)
  )
    throw new PublishError(
      'ASSET_INVALID',
      'Generated asset helper is out of date. Run soyli assets sync.',
    );
  return lock;
}
